'use client';
import { motion } from 'framer-motion';
import { Reveal } from '@/components/ui/animated';
const services = [{ title:'AI Automation Systems', body:'Decision-support automations, internal copilots, and controlled execution flows that reduce operator drag without surrendering standards.', detail:'Ideal for teams drowning in manual triage, repetitive client handling, and unstructured knowledge.' },{ title:'Business Infrastructure Setup', body:'Backend architecture for intake, fulfillment, client operations, and internal routing with clean administrative control.', detail:'Designed for service businesses, agencies, and operators scaling beyond founder memory.' },{ title:'Telegram + Stripe Systems', body:'Command surfaces, payment orchestration, gated access, and delivery logic built around high-speed conversion.', detail:'Useful for memberships, offers, high-touch sales flows, and private client environments.' },{ title:'Website + Backend Integration', body:'Front-end authority paired with backend precision: forms, CRM logic, APIs, automations, and reporting connected with intent.', detail:'For brands that need a site to function as an asset, not a brochure.' }];
/**
 * Renders the Services page, including an introductory header and a responsive grid of animated service cards.
 *
 * @returns The React element for the Services page containing the header, description, and animated service cards.
 */
export default function ServicesPage() { return <div className="shell py-24"><Reveal className="max-w-3xl"><p className="eyebrow mb-4">Services</p><h1 className="font-serif text-5xl sm:text-6xl">Modular systems. Operator-grade depth.</h1><p className="mt-6 text-lg leading-8 text-white/58">Every engagement is composed as infrastructure, not a pile of disconnected tasks.</p></Reveal><div className="mt-16 grid gap-6 lg:grid-cols-2">{services.map((service, index) => <motion.article key={service.title} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * 0.08, duration: 0.55 }} whileHover={{ y: -6, borderColor: 'rgba(212,175,55,0.32)' }} className="group rounded-[2rem] border border-gold-400/10 bg-white/[0.03] p-8 shadow-halo"><div className="flex items-start justify-between gap-6"><div><p className="text-sm uppercase tracking-luxe text-gold-300/75">0{index + 1}</p><h2 className="mt-6 font-serif text-3xl">{service.title}</h2></div><div className="mt-1 h-11 w-11 rounded-full border border-white/10 bg-white/[0.04] transition group-hover:border-gold-400/30 group-hover:bg-gold-400/10" /></div><p className="mt-6 leading-7 text-white/60">{service.body}</p><div className="mt-8 rounded-[1.5rem] border border-white/8 bg-black/20 p-5 text-sm leading-7 text-white/52">{service.detail}</div></motion.article>)}</div></div>; }
