'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { AnimatePresence, motion } from 'framer-motion';
const navItems = [{ href:'/', label:'Home' },{ href:'/services', label:'Services' },{ href:'/systems', label:'Systems' },{ href:'/about', label:'About' },{ href:'/contact', label:'Apply' }];
export function SiteFrame({ children }: { children: React.ReactNode }) {
  const pathname = usePathname();
  return <div className="min-h-screen bg-obsidian text-white"><div className="pointer-events-none fixed inset-0 bg-hero-radial opacity-90" /><header className="sticky top-0 z-50 border-b border-white/5 bg-black/45 backdrop-blur-2xl"><div className="shell flex h-20 items-center justify-between"><Link href="/" className="group flex items-center gap-4"><div className="h-10 w-10 rounded-full border border-gold-400/30 bg-gradient-to-br from-gold-400/20 to-transparent shadow-glow" /><div><p className="eyebrow">Lowkey Luxury</p><p className="text-sm text-white/60 transition group-hover:text-white/80">Infrastructure over effort</p></div></Link><nav className="hidden items-center gap-8 md:flex">{navItems.map((item)=>{const active=pathname===item.href;return <Link key={item.href} href={item.href} className={`text-sm transition ${active ? 'text-gold-200' : 'text-white/62 hover:text-white'}`}>{item.label}</Link>;})}</nav></div></header><AnimatePresence mode="wait"><motion.main key={pathname} initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -12 }} transition={{ duration: 0.55, ease: [0.22,1,0.36,1] }} className="relative z-10">{children}</motion.main></AnimatePresence><footer className="border-t border-white/5 py-10"><div className="shell flex flex-col gap-4 text-sm text-white/45 md:flex-row md:items-center md:justify-between"><p>Built for operators who value permanence.</p><div className="flex gap-6"><Link href="/services" className="link-hover">Capabilities</Link><Link href="/systems" className="link-hover">Stacks</Link><Link href="/contact" className="link-hover">Apply</Link></div></div></footer></div>;
}
